"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { knowledgeApi, type AnalysisResult, type AskResult, type EntryType, type KnowledgeEntry } from "./services/api";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import "./answer.css";

type Page = "Dashboard" | "Log Knowledge" | "Knowledge Base" | "AI Assistant";

type ListEntry={id:string;type:EntryType;title:string;summary:string;project:string;module:string;tags:string[];status:string;updated:string};
const toListEntry=(e:KnowledgeEntry):ListEntry=>({id:e.id,type:e.entryType,title:e.title,summary:e.summary,project:e.project??"Unassigned",module:e.module??"General",tags:e.tags,status:e.status==="NeedsReview"?"Needs review":e.status,updated:new Date(e.updatedAt).toLocaleDateString()});

const nav: { label: Page; icon: string }[] = [
  { label: "Dashboard", icon: "⌂" }, { label: "Log Knowledge", icon: "+" },
  { label: "Knowledge Base", icon: "◇" }, { label: "AI Assistant", icon: "✦" },
];

export default function Home() {
  const [page, setPage] = useState<Page>("Dashboard");
  const [collapsed, setCollapsed] = useState(false);
  const [query, setQuery] = useState("");
  const [analyzed, setAnalyzed] = useState(false);
  const [raw, setRaw] = useState("");
  const knowledgeQuery=useQuery({queryKey:["knowledge",query],queryFn:()=>knowledgeApi.list(query)});
  const entries=knowledgeQuery.data?.map(toListEntry)??[];
  const filtered = useMemo(() => entries.filter(e => `${e.title} ${e.summary} ${e.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [entries,query]);

  return <div className={`shell ${collapsed ? "is-collapsed" : ""}`}>
    <aside className="sidebar">
      <div className="brand"><div className="brandmark">K</div><div className="brandtext"><strong>Knowledge Desk</strong><span>Engineering intelligence</span></div></div>
      <nav>{nav.map(item => <button key={item.label} className={page === item.label ? "active" : ""} onClick={() => setPage(item.label)}><span className="navicon">{item.icon}</span><span>{item.label}</span></button>)}</nav>
      <div className="future"><p>COMING LATER</p>{["Code Intelligence", "Jira", "Documents"].map(x => <div key={x}><span>○</span><span>{x}</span></div>)}</div>
      <div className="sidebar-foot"><div className="avatar">AV</div><div><strong>Akash Vishnoi</strong><span>Engineering</span></div><button aria-label="Collapse sidebar" onClick={() => setCollapsed(!collapsed)}>‹</button></div>
    </aside>
    <main>
      <header><button className="mobile-menu" onClick={() => setCollapsed(!collapsed)}>☰</button><div className="global-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} onFocus={() => setPage("Knowledge Base")} placeholder="Search knowledge, projects, or ask a question…"/><kbd>⌘ K</kbd></div><button className="icon-button">?</button><button className="icon-button">♢</button></header>
      <div className="content">{page === "Dashboard" && <Dashboard navigate={setPage} entries={entries}/>} {page === "Knowledge Base" && <KnowledgeBase query={query} setQuery={setQuery} entries={filtered}/>} {page === "Log Knowledge" && <Capture raw={raw} setRaw={setRaw} analyzed={analyzed} setAnalyzed={setAnalyzed}/>} {page === "AI Assistant" && <Assistant/>}</div>
    </main>
  </div>;
}

function Dashboard({navigate,entries}:{navigate:(p:Page)=>void,entries:ListEntry[]}) {
 const issues=entries.filter(e=>e.type==="Issue"||e.type==="Troubleshooting").length;const workflows=entries.filter(e=>e.type==="Workflow"||e.type==="HowTo").length;const review=entries.filter(e=>e.status.toLowerCase().includes("review")).length;
 return <><div className="page-title"><div><p>{new Intl.DateTimeFormat(undefined,{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</p><h1>Knowledge overview</h1><span>Here’s what your team knows today.</span></div><button className="primary" onClick={() => navigate("Log Knowledge")}>＋ Log knowledge</button></div>
  <section className="hero"><div><span className="eyebrow">KNOWLEDGE ASSISTANT</span><h2>What can we help you solve?</h2><p>Ask a question and get an answer grounded in your team’s knowledge.</p><button onClick={() => navigate("AI Assistant")}>Ask Knowledge Desk <span>→</span></button></div><div className="orb"><span>✦</span></div></section>
  <div className="stats"><Stat label="Total knowledge" value={String(entries.length)} note="Persisted entries"/><Stat label="Issues & troubleshooting" value={String(issues)} note="Available to the team"/><Stat label="Workflows & how-tos" value={String(workflows)} note="Reusable guidance"/><Stat label="Needs review" value={String(review)} note={review?"Action recommended":"Nothing pending"} warn={review>0}/></div>
  <div className="grid"><section className="panel recent"><div className="panel-head"><div><h3>Recently added</h3><p>Latest knowledge shared by your team</p></div><button onClick={()=>navigate("Knowledge Base")}>View all →</button></div>{entries.slice(0,5).map(e=><Entry key={e.id} entry={e}/>)}</section><section className="panel quick"><div className="panel-head"><div><h3>Quick actions</h3><p>Capture or find what matters</p></div></div><button onClick={()=>navigate("Log Knowledge")}><span className="quick-icon coral">＋</span><div><strong>Log knowledge</strong><p>Turn an experience into reusable guidance</p></div><b>→</b></button><button onClick={()=>navigate("AI Assistant")}><span className="quick-icon lavender">✦</span><div><strong>Ask the assistant</strong><p>Get answers from internal knowledge</p></div><b>→</b></button><div className="review-callout"><span>!</span><div><strong>{review} entries need review</strong><p>Help keep team knowledge accurate.</p></div></div></section></div>
 </>;
}

function Stat({label,value,note,warn}:{label:string,value:string,note:string,warn?:boolean}) { return <div className="stat"><div><span>{label}</span><strong>{value}</strong></div><p className={warn?"warning":""}>{warn?"●":"↗"} {note}</p></div> }
function Entry({entry}:{entry:ListEntry}) { return <article className="entry"><div className={`type-icon ${entry.type.toLowerCase()}`}>{entry.type === "Issue" ? "!" : entry.type === "Workflow" ? "↳" : "?"}</div><div className="entry-copy"><div><span className="pill">{entry.type}</span><span className={`status ${entry.status.includes("review")?"review":""}`}>{entry.status}</span><span className="updated">{entry.updated}</span></div><h4>{entry.title}</h4><p>{entry.summary}</p><div className="meta"><span>{entry.project}</span><i>•</i><span>{entry.module}</span>{entry.tags.map(t=><em key={t}>{t}</em>)}</div></div></article> }

function KnowledgeBase({query,setQuery,entries:all}:{query:string;setQuery:(s:string)=>void;entries:ListEntry[]}) { const [type,setType]=useState("All");const [project,setProject]=useState("All");const types=[...new Set(all.map(e=>e.type))];const projects=[...new Set(all.map(e=>e.project))];const shown=all.filter(e=>(type==="All"||e.type===type)&&(project==="All"||e.project===project));return <><div className="page-title"><div><p>LIBRARY</p><h1>Knowledge base</h1><span>Search and reuse practical knowledge from across your team.</span></div></div><div className="library-tools"><div className="library-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by title, problem, technology…"/></div></div><div className="library-layout"><aside className="filters"><h3>Refine results</h3><label>Entry type<select value={type} onChange={e=>setType(e.target.value)}><option>All</option>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option>All</option>{projects.map(x=><option key={x}>{x}</option>)}</select></label></aside><section className="results"><div className="results-head"><strong>{shown.length} results</strong></div>{shown.length ? shown.map(e=><Entry key={e.id} entry={e}/>) : <div className="empty"><span>⌕</span><h3>No knowledge found</h3><p>Try a broader search or log what you learned.</p></div>}</section></div></> }

function Capture({raw,setRaw,analyzed,setAnalyzed}:{raw:string;setRaw:(s:string)=>void;analyzed:boolean;setAnalyzed:(b:boolean)=>void}) {
 const schema=z.object({rawInput:z.string().min(20,"Please provide at least 20 characters.").max(20000),entryType:z.enum(["Issue","Workflow","Knowledge","Troubleshooting","HowTo","Decision","KnownLimitation"]),project:z.string().max(200),module:z.string().max(200)});type Form=z.infer<typeof schema>;const form=useForm<Form>({resolver:zodResolver(schema),defaultValues:{rawInput:raw,entryType:"Issue",project:"",module:""}});const [analysis,setAnalysis]=useState<AnalysisResult|null>(null);const selected=form.watch("entryType");const mutation=useMutation({mutationFn:(v:Form)=>knowledgeApi.analyze({...v,project:v.project||undefined,module:v.module||undefined}),onSuccess:r=>{setAnalysis(r);setAnalyzed(true)}});const submit=form.handleSubmit(v=>{setRaw(v.rawInput);mutation.mutate(v)});
 const choices:{value:EntryType;label:string}[]=[{value:"Issue",label:"Issue"},{value:"Workflow",label:"Workflow"},{value:"Knowledge",label:"Knowledge"},{value:"Troubleshooting",label:"Troubleshooting"},{value:"HowTo",label:"How-To"},{value:"Decision",label:"Decision"},{value:"KnownLimitation",label:"Known Limitation"}];return <><div className="page-title"><div><p>CAPTURE</p><h1>Log knowledge</h1><span>Describe what happened naturally. Knowledge Desk will structure it for you.</span></div></div><div className="steps"><span className="done">1</span><b className={analyzed?"done-line":""}/><span className={analyzed?"done":""}>2</span><p>Describe</p><p>Review & save</p></div>{!analyzed?<form className="capture-card" onSubmit={submit}><label>What are you capturing?</label><div className="type-picks">{choices.map(x=><button type="button" aria-pressed={selected===x.value} className={selected===x.value?"selected":""} onClick={()=>form.setValue("entryType",x.value,{shouldDirty:true})} key={x.value}>{x.label}</button>)}</div><label>Describe the issue, solution, workflow, or knowledge</label><textarea {...form.register("rawInput")} placeholder="Describe what happened, what you learned, and any resolution…"/>{form.formState.errors.rawInput&&<p className="warning">{form.formState.errors.rawInput.message}</p>}<div className="capture-options"><input {...form.register("project")} placeholder="Project (optional)"/><input {...form.register("module")} placeholder="Module (optional)"/></div>{mutation.error&&<p className="warning">{mutation.error.message}</p>}<button type="submit" className="primary analyze" disabled={mutation.isPending}>{mutation.isPending?"Analyzing…":"✦ Analyze with AI"}</button></form>:analysis&&<Review analysis={analysis} onBack={()=>setAnalyzed(false)}/>}</>;
}

function Review({analysis,onBack}:{analysis:AnalysisResult;onBack:()=>void}) {
 const client=useQueryClient();const [entry,setEntry]=useState(analysis.entry);const save=useMutation({mutationFn:()=>knowledgeApi.create(entry),onSuccess:()=>{client.invalidateQueries({queryKey:["knowledge"]});alert("Knowledge saved and indexed.");onBack()}});const field=(key:keyof KnowledgeEntry,value:string)=>setEntry({...entry,[key]:value});
 return <section className="review-form"><div className="ai-banner"><div>✦</div><div><strong>Analysis ready</strong><p>Review every field before saving. Nothing is saved until you confirm.</p></div><span><b>{Math.round(entry.confidenceScore*100)}%</b> confidence</span></div>{analysis.potentialDuplicates.length>0&&<div className="duplicate"><strong>Possible related knowledge</strong><p>{analysis.potentialDuplicates[0].title} · {Math.round(analysis.potentialDuplicates[0].similarity*100)}% similar</p></div>}<div className="form-grid"><label>Title <input value={entry.title} onChange={e=>field("title",e.target.value)}/></label><label>Category <input value={entry.category??""} onChange={e=>field("category",e.target.value)}/></label><label className="wide">Summary <textarea value={entry.summary} onChange={e=>field("summary",e.target.value)}/></label><label>Problem <textarea value={entry.problem??""} onChange={e=>field("problem",e.target.value)}/></label><label>Root cause <textarea value={entry.rootCause??""} onChange={e=>field("rootCause",e.target.value)}/></label><label>Solution <textarea value={entry.solution??""} onChange={e=>field("solution",e.target.value)}/></label><label>Prevention <textarea value={entry.prevention??""} onChange={e=>field("prevention",e.target.value)}/></label></div>{save.error&&<p className="warning">{save.error.message}</p>}<div className="form-actions"><button onClick={onBack}>← Back</button><button className="primary" disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?"Saving…":"Confirm & save"}</button></div></section>;
}

function Assistant() {
 const [question,setQuestion]=useState("");const [answer,setAnswer]=useState<AskResult|null>(null);const ask=useMutation({mutationFn:(q:string)=>knowledgeApi.ask(q),onSuccess:setAnswer});const submit=(q=question)=>{if(q.trim()){setQuestion(q);ask.mutate(q)}};
 return <div className="assistant-page"><div className="assistant-intro"><div className="assistant-mark">✦</div><p>AI ASSISTANT</p><h1>Ask your team’s knowledge</h1><span>Answers are grounded in verified internal entries—and clearly say when evidence is limited.</span></div><div className="chat"><div className="chat-empty"><p>Try asking</p>{["Why can premium mismatch happen because of age?","How do we validate a production release?","Why would a MassTransit consumer stop after deployment?"].map(q=><button key={q} onClick={()=>submit(q)}>{q}<span>→</span></button>)}</div>{ask.isPending&&<div className="thinking">✦ Searching verified knowledge…</div>}{ask.error&&<div className="thinking">{ask.error.message}</div>}{answer&&<div className="answer"><div className="grounded">{answer.grounded?"● Grounded in internal knowledge":"○ Not enough internal evidence"}</div><AnswerBody text={answer.answer}/>{answer.sources.map((source,i)=><div className="source" key={source.knowledgeEntryId}><span>{i+1}</span><div><small>INTERNAL SOURCE · {Math.round(source.similarity*100)}% MATCH</small><strong>{source.title}</strong></div></div>)}</div>}<div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question about your projects, issues, or workflows…"/><button onClick={()=>submit()}>↑</button><small>Knowledge Desk answers from internal knowledge and may say when it doesn’t know.</small></div></div></div>;
}

function AnswerBody({text}:{text:string}) { const lines=text.split(/\r?\n/);return <div className="answer-body">{lines.map((line,i)=>{const value=line.trim();if(!value)return <div className="answer-gap" key={i}/>;if(/^#{1,3}\s/.test(value))return <h3 key={i}>{value.replace(/^#{1,3}\s/,"")}</h3>;if(/^[-*]\s/.test(value))return <div className="answer-list-item" key={i}><span>•</span><p>{value.replace(/^[-*]\s/,"")}</p></div>;const numbered=value.match(/^(\d+)\.\s+(.*)$/);if(numbered)return <div className="answer-list-item" key={i}><span>{numbered[1]}.</span><p>{numbered[2]}</p></div>;return <p key={i}>{value}</p>})}</div> }
