using InternalKnowledge.AI;
using InternalKnowledge.Application;
using InternalKnowledge.Domain;
using Microsoft.Extensions.Options;

namespace InternalKnowledge.UnitTests;
public sealed class KnowledgeAnalysisTests
{
    [Fact] public async Task Premium_age_note_is_structured_without_inventing_data(){var service=new KnowledgeAnalysisService(new UnusedLlm(),new NoMatches(),Options.Create(new AiOptions()));var result=await service.AnalyzeAsync(new("Premium mismatch happened because age used current date instead of policy start date. We fixed the reference date and added boundary tests.",KnowledgeEntryType.Issue,"Health Fresh","Rating"),default);Assert.Contains("premium mismatch",result.Entry.Title,StringComparison.OrdinalIgnoreCase);Assert.NotNull(result.Entry.RootCause);Assert.NotNull(result.Entry.Solution);Assert.True(result.Entry.ConfidenceScore>=.8m);}
    [Fact] public async Task Incomplete_note_reports_missing_information(){var service=new KnowledgeAnalysisService(new UnusedLlm(),new NoMatches(),Options.Create(new AiOptions()));var result=await service.AnalyzeAsync(new("The integration failed intermittently during the morning deployment window.",KnowledgeEntryType.Issue,null,null),default);Assert.Null(result.Entry.RootCause);Assert.NotEmpty(result.MissingInformation);Assert.NotEmpty(result.SuggestedQuestions);}
    [Fact] public void Searchable_content_contains_solution_and_metadata(){var entry=new KnowledgeEntry{Title="Queue issue",Summary="Consumer stopped",OriginalInput="x",Solution="Register endpoint",Project="Platform",Tags=["MassTransit"]};var text=KnowledgeAnalysisService.BuildSearchable(entry);Assert.Contains("Register endpoint",text);Assert.Contains("MassTransit",text);Assert.Contains("Platform",text);}
    [Fact] public async Task OpenAi_extraction_maps_issue_fields(){var json="""{"title":"Kong rejects request without API key","summary":"Swagger request returned a Kong authentication error.","problem":"Kong returned No API Key found in request.","rootCause":"The apikey header was missing or contained an invalid value.","solution":"Send a valid apikey header.","prevention":"Validate API key configuration before using Swagger.","confidenceScore":0.95,"tags":["Kong","API Key"],"technologies":["Swagger"],"missingInformation":[],"suggestedQuestions":[]}""";var service=new KnowledgeAnalysisService(new FixedLlm(json),new NoMatches(),Options.Create(new AiOptions{Provider="OpenAI"}));var result=await service.AnalyzeAsync(new("Kong Error: No API Key found in request. This happens when apikey is missing or wrong.",KnowledgeEntryType.Troubleshooting,null,null),default);Assert.NotNull(result.Entry.Problem);Assert.NotNull(result.Entry.RootCause);Assert.NotNull(result.Entry.Solution);Assert.NotNull(result.Entry.Prevention);}
    [Fact] public async Task Local_provider_splits_independent_paragraphs(){var service=new KnowledgeAnalysisService(new UnusedLlm(),new NoMatches(),Options.Create(new AiOptions{Provider="Local"}));var result=await service.AnalyzeAsync(new("Billing failed because the token expired. We fixed token refresh and added tests.\n\nSearch failed because the index was stale. We fixed the indexing worker and added monitoring.",KnowledgeEntryType.Issue,null,null),default);Assert.Equal(2,result.SuggestedEntries.Count);}
    [Fact] public void Chunker_indexes_all_grounding_fields(){var entry=new KnowledgeEntry{Title="Title",Summary="Summary",OriginalInput="note",Problem="Problem",RootCause="Cause",Solution="Solution",Prevention="Prevention",DetailedContent="Details",Technologies=["PostgreSQL"]};var chunks=InternalKnowledge.Persistence.KnowledgeChunker.Create(entry);Assert.Contains(chunks,x=>x.Type=="RootCause"&&x.Content=="Cause");Assert.Contains(chunks,x=>x.Type=="Solution");Assert.Contains(chunks,x=>x.Type=="Metadata"&&x.Content.Contains("PostgreSQL"));}
    [Fact] public async Task Local_provider_keeps_one_problem_with_supporting_paragraphs_together(){var service=new KnowledgeAnalysisService(new UnusedLlm(),new NoMatches(),Options.Create(new AiOptions{Provider="Local"}));var result=await service.AnalyzeAsync(new("Checkout failed because the token expired.\n\nThe resolution refreshed the token and added monitoring for expiry.",KnowledgeEntryType.Issue,null,null),default);Assert.Single(result.SuggestedEntries);Assert.Contains("resolution",result.Entry.OriginalInput,StringComparison.OrdinalIgnoreCase);}
    [Theory][InlineData(1,10)][InlineData(2,20)][InlineData(3,40)][InlineData(20,5120)] public void Retry_delay_is_bounded_exponential(int attempt,int seconds)=>Assert.Equal(TimeSpan.FromSeconds(seconds),InternalKnowledge.Persistence.IndexingRetry.Delay(attempt));
    private sealed class NoMatches:ISemanticSearchService{public Task<IReadOnlyList<KnowledgeSearchResult>> SearchAsync(string q,int l,string? p,string? m,CancellationToken ct)=>Task.FromResult<IReadOnlyList<KnowledgeSearchResult>>([]);}
    private sealed class UnusedLlm:ILLMService{public Task<string> CompleteAsync(string p,object i,CancellationToken ct)=>throw new InvalidOperationException();}
    private sealed class FixedLlm(string value):ILLMService{public Task<string> CompleteAsync(string p,object i,CancellationToken ct)=>Task.FromResult(value);}
}
