using FluentValidation;
using InternalKnowledge.AI;
using InternalKnowledge.Application;
using InternalKnowledge.Domain;
using InternalKnowledge.Persistence;
using Microsoft.EntityFrameworkCore;
using Serilog;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Options;

var builder=WebApplication.CreateBuilder(args);
builder.Host.UseSerilog((ctx,c)=>c.ReadFrom.Configuration(ctx.Configuration).Enrich.FromLogContext().WriteTo.Console());
builder.Services.AddProblemDetails();builder.Services.AddExceptionHandler<GlobalExceptionHandler>();builder.Services.AddOpenApi();builder.Services.AddValidatorsFromAssemblyContaining<Program>();
builder.Services.ConfigureHttpJsonOptions(o=>o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()));
builder.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.WithOrigins(builder.Configuration["FrontendUrl"]??"http://localhost:3000").AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddKnowledgeAi(builder.Configuration);builder.Services.AddKnowledgePersistence(builder.Configuration);
var app=builder.Build();app.UseExceptionHandler();app.UseSerilogRequestLogging();app.UseCors();if(app.Environment.IsDevelopment())app.MapOpenApi();
if(!app.Environment.IsEnvironment("Testing")){await using var scope=app.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<KnowledgeDbContext>();await db.Database.MigrateAsync();}

app.MapPost("/api/knowledge/analyze",async(AnalyzeKnowledgeRequest request,IValidator<AnalyzeKnowledgeRequest> validator,IKnowledgeAnalysisService service,CancellationToken ct)=>{var v=await validator.ValidateAsync(request,ct);return !v.IsValid?Results.ValidationProblem(v.ToDictionary()):Results.Ok(await service.AnalyzeAsync(request,ct));});
app.MapPost("/api/knowledge",async(KnowledgeEntry entry,bool allowDuplicate,IValidator<KnowledgeEntry> validator,IKnowledgeRepository repo,ISemanticSearchService search,IOptions<AiOptions> options,IKnowledgeIndexingQueue queue,KnowledgeDbContext db,CancellationToken ct)=>{var v=await validator.ValidateAsync(entry,ct);if(!v.IsValid)return Results.ValidationProblem(v.ToDictionary());if(await repo.GetAsync(entry.Id,ct)is not null)return Results.Conflict(new{code="id_already_exists",message="Use the update endpoint for an existing knowledge entry."});var duplicate=await FindDuplicate(entry,search,options.Value.DuplicateSimilarityThreshold,ct);if(duplicate is not null&&!allowDuplicate)return DuplicateConflict(duplicate);await using var tx=await db.Database.BeginTransactionAsync(ct);await repo.SaveAsync(entry,ct);await db.AddRevisionAsync(entry,ct);await queue.EnqueueAsync(entry.Id,ct);await tx.CommitAsync(ct);return Results.Created($"/api/knowledge/{entry.Id}",entry);});
app.MapPut("/api/knowledge/{id:guid}",async(Guid id,KnowledgeEntry entry,IValidator<KnowledgeEntry> validator,IKnowledgeRepository repo,IKnowledgeIndexingQueue queue,KnowledgeDbContext db,CancellationToken ct)=>{if(id!=entry.Id)return Results.BadRequest();if(await repo.GetAsync(id,ct) is null)return Results.NotFound();var v=await validator.ValidateAsync(entry,ct);if(!v.IsValid)return Results.ValidationProblem(v.ToDictionary());entry.UpdatedAt=DateTimeOffset.UtcNow;await using var tx=await db.Database.BeginTransactionAsync(ct);await repo.SaveAsync(entry,ct);await db.AddRevisionAsync(entry,ct);await queue.EnqueueAsync(id,ct);await tx.CommitAsync(ct);return Results.Ok(entry);});
app.MapGet("/api/knowledge/{id:guid}",async(Guid id,IKnowledgeRepository repo,CancellationToken ct)=>await repo.GetAsync(id,ct) is { } e?Results.Ok(e):Results.NotFound());
app.MapGet("/api/knowledge",async([AsParameters] KnowledgeListParameters p,IKnowledgeRepository repo,CancellationToken ct)=>Results.Ok(await repo.ListAsync(new(p.Query,p.EntryType,p.Project,p.Module,p.Severity,p.Status,p.Technology,p.Tag,p.Sort??"updatedDesc",Math.Max(p.Page??1,1),Math.Clamp(p.PageSize??20,1,100),p.IncludeArchived??false),ct)));
app.MapGet("/api/knowledge/{id:guid}/revisions",async(Guid id,KnowledgeDbContext db,CancellationToken ct)=>Results.Ok(await db.KnowledgeRevisions.AsNoTracking().Where(x=>x.KnowledgeEntryId==id).OrderByDescending(x=>x.RevisionNumber).ToListAsync(ct)));
app.MapPost("/api/knowledge/{id:guid}/archive",async(Guid id,IKnowledgeRepository repo,IKnowledgeIndexingQueue queue,KnowledgeDbContext db,CancellationToken ct)=>await SetStatus(id,KnowledgeStatus.Archived,repo,queue,db,ct));
app.MapPost("/api/knowledge/{id:guid}/restore",async(Guid id,IKnowledgeRepository repo,IKnowledgeIndexingQueue queue,KnowledgeDbContext db,CancellationToken ct)=>await SetStatus(id,KnowledgeStatus.Active,repo,queue,db,ct));
app.MapPost("/api/search/semantic",async(SemanticSearchRequest request,IValidator<SemanticSearchRequest> validator,ISemanticSearchService search,CancellationToken ct)=>{var v=await validator.ValidateAsync(request,ct);return !v.IsValid?Results.ValidationProblem(v.ToDictionary()):Results.Ok(await search.SearchAsync(request.Query,request.Limit,request.Project,request.Module,ct));});
app.MapPost("/api/assistant/ask",async(AskRequest request,IValidator<AskRequest> validator,IKnowledgeAnswerService service,KnowledgeDbContext db,CancellationToken ct)=>{var v=await validator.ValidateAsync(request,ct);if(!v.IsValid)return Results.ValidationProblem(v.ToDictionary());var answer=await service.AskAsync(request,ct);db.QuestionHistory.Add(new(){Question=request.Question,Answer=answer.Answer,Grounded=answer.Grounded});await db.SaveChangesAsync(ct);return Results.Ok(answer);});
app.MapGet("/api/knowledge/{id:guid}/similar",async(Guid id,IKnowledgeRepository repo,ISemanticSearchService search,CancellationToken ct)=>await repo.GetAsync(id,ct) is { } e?Results.Ok(await search.SearchAsync($"{e.Title} {e.Summary}",6,e.Project,e.Module,ct)):Results.NotFound());
app.MapPost("/api/knowledge/{id:guid}/reindex",async(Guid id,IKnowledgeRepository repo,IKnowledgeIndexingQueue queue,CancellationToken ct)=>{if(await repo.GetAsync(id,ct)is null)return Results.NotFound();await queue.EnqueueAsync(id,ct);return Results.Accepted();});
app.MapPost("/api/knowledge/{id:guid}/feedback",async(Guid id,FeedbackRequest request,IKnowledgeRepository repo,KnowledgeDbContext db,CancellationToken ct)=>{if(await repo.GetAsync(id,ct)is null)return Results.NotFound();db.KnowledgeFeedback.Add(new(){KnowledgeEntryId=id,Helpful=request.Helpful,Comment=request.Comment});await db.SaveChangesAsync(ct);return Results.NoContent();});
app.MapPost("/api/admin/reindex",async(ReindexRequest request,IKnowledgeIndexingQueue queue,CancellationToken ct)=>{foreach(var id in request.EntryIds.Distinct().Take(100))await queue.EnqueueAsync(id,ct);return Results.Accepted();});
app.MapGet("/health/live",()=>Results.Ok(new{status="healthy",utc=DateTimeOffset.UtcNow}));
app.MapGet("/health/ready",async(KnowledgeDbContext db,CancellationToken ct)=>await db.Database.CanConnectAsync(ct)?Results.Ok(new{status="ready",database="connected"}):Results.Json(new{status="unhealthy",database="disconnected"},statusCode:503));
app.MapGet("/health",async(KnowledgeDbContext db,CancellationToken ct)=>await db.Database.CanConnectAsync(ct)?Results.Ok(new{status="healthy",database="connected",utc=DateTimeOffset.UtcNow}):Results.Json(new{status="unhealthy",database="disconnected",utc=DateTimeOffset.UtcNow},statusCode:503));
app.MapGet("/api/admin/metrics",async(KnowledgeDbContext db,CancellationToken ct)=>Results.Ok(new{indexing=KnowledgeMetrics.Snapshot(),jobs=new{pending=await db.IndexingJobs.CountAsync(x=>x.Status==IndexingJobStatus.Pending,ct),processing=await db.IndexingJobs.CountAsync(x=>x.Status==IndexingJobStatus.Processing,ct),failed=await db.IndexingJobs.CountAsync(x=>x.Status==IndexingJobStatus.Failed,ct)},utc=DateTimeOffset.UtcNow}));
app.Run();

static async Task<KnowledgeSearchResult?> FindDuplicate(KnowledgeEntry e,ISemanticSearchService search,double threshold,CancellationToken ct)=>(await search.SearchAsync($"{e.Title} {e.Summary} {e.Problem} {e.RootCause} {e.Solution}",5,e.Project,e.Module,ct)).FirstOrDefault(x=>x.KnowledgeEntryId!=e.Id&&x.Similarity>=threshold);
static IResult DuplicateConflict(KnowledgeSearchResult match)=>Results.Conflict(new{code="duplicate_detected",message="A likely duplicate already exists. Update it or explicitly allow a separate occurrence.",match});
static async Task<IResult> SetStatus(Guid id,KnowledgeStatus status,IKnowledgeRepository repo,IKnowledgeIndexingQueue queue,KnowledgeDbContext db,CancellationToken ct){var e=await repo.GetAsync(id,ct);if(e is null)return Results.NotFound();e.Status=status;e.UpdatedAt=DateTimeOffset.UtcNow;await using var tx=await db.Database.BeginTransactionAsync(ct);await repo.SaveAsync(e,ct);await db.AddRevisionAsync(e,ct);await queue.EnqueueAsync(id,ct);await tx.CommitAsync(ct);return Results.NoContent();}
public partial class Program{}
public record SemanticSearchRequest(string Query,int Limit=10,string? Project=null,string? Module=null);public record FeedbackRequest(bool Helpful,string? Comment);public record ReindexRequest(Guid[] EntryIds);
public sealed class KnowledgeListParameters { public string? Query {get;set;} public KnowledgeEntryType? EntryType {get;set;} public string? Project {get;set;} public string? Module {get;set;} public KnowledgeSeverity? Severity {get;set;} public KnowledgeStatus? Status {get;set;} public string? Technology {get;set;} public string? Tag {get;set;} public string? Sort {get;set;} public int? Page {get;set;} public int? PageSize {get;set;} public bool? IncludeArchived {get;set;} }
